package com.example.pingpongx

object Constants {

    val KEY_EXTRA_PLAYER_1 = "KEY_EXTRA_PLAYER_1"
    val KEY_EXTRA_PLAYER_2 = "KEY_EXTRA_PLAYER_2"
    val KEY_EXTRA_SCORE_PLAYER_1 = "KEY_EXTRA_SCORE_PLAYER_1"
    val KEY_EXTRA_SCORE_PLAYER_2 = "KEY_EXTRA_SCORE_PLAYER_2"
}